#!/bin/bash
FIFO="$HOME/.cache/cmdq/cmdq.sock"
LOCK="$HOME/.cache/cmdq/cmdq.lock"

mkdir -p $(dirname "$FIFO")
if  [! -p "$FIFO" ] ; then
  echo "Creating pipe at $FIFO"
  if [ -e "$FIFO" ] ; then
    echo "removing old $FIFO"
    rm "$FIFO"
  fi
  mkfifo "$FIFO"
fi

echocmd() {
  if [ $# -lt 1 -o -z "$1" ] ; then
    return
  fi
  echo "\$ $@"
  bash -i -l -c "$@"
  local res=$?
  echo "command exited with $res"
  return $res
}

# Open the script as reader and writer of FIFO to keep xargs from receiving EOF
exec 3<>"$FIFO"
export -f echocmd
xargs -r -a "$FIFO" -0 -I{} \
  flock "$LOCK" \
  bash -i -l -c 'echocmd "$@"' _ {}

